
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[306] =
    {   0,
        1,    1,   80,   80,   94,   93,    2,    5,    1,   93,
       83,   88,   93,   67,   93,   93,   84,   85,   65,   63,
       72,   64,   66,   76,   73,   68,   62,   69,   92,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   86,   93,
       87,   62,   80,   81,   93,    2,    1,   59,    0,    0,
       78,    0,    0,   49,    0,   51,   61,    0,   55,   70,
       52,   71,   54,   53,    0,   76,   92,   92,   92,   56,
       58,   57,   50,   92,   50,   50,    0,   48,   48,   48,
       48,   48,   48,   48,   19,   48,   48,   48,   48,   48,

       29,   48,   48,   23,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       60,   79,   80,    0,    0,    0,    0,   49,   49,    0,
        4,    0,   52,   77,   92,   92,   50,   92,   50,    0,
        0,    0,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   26,   48,   48,   48,   43,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   20,
       48,   48,   48,   48,   48,   17,   48,   48,   48,    0,
        0,    0,    0,   49,   49,   49,    0,   89,   52,   91,
        0,   90,    0,    0,    0,   48,   48,   13,   14,   48,

       48,   48,   48,   22,   48,   48,   48,   10,    9,   48,
       12,   48,    8,   48,   48,   48,   48,   48,   48,   44,
       48,   48,   48,   48,   34,   48,   48,   48,   41,   48,
       48,    0,    3,    0,   91,    0,    0,   48,    7,   15,
       48,   48,   48,   48,   25,   48,    0,   46,   48,   48,
       48,   47,   32,   48,   48,   48,   48,   48,   39,   48,
       11,   48,   45,   82,    0,   48,   48,   48,   21,   24,
       48,   75,   48,   31,   48,   33,   35,   28,   36,   37,
       48,   48,    0,    6,   48,   18,   38,   48,   42,   48,
       48,    0,   16,   30,   40,   27,    0,    0,    0,    0,

        0,    0,    0,   74,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,   25,   26,   27,   28,   28,   29,   28,
       30,   31,   28,   28,   28,   28,   28,   32,   28,   28,
       28,   28,   33,   28,   28,   28,   28,   28,   28,   28,
       34,    1,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   28,   47,   48,   49,   50,
       51,   52,   28,   53,   54,   55,   56,   57,   58,   59,
       60,   28,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    5,    1,
        1,    6,    7,    1,    1,    1,    1,    8,    1,    9,
        1,    1,   10,    1,   11,   12,   12,   12,   12,   12,
       12,   12,   12,   13,    1,    1,    9,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[326] =
    {   0,
        0,  668,   61,   62,  690,  733,  687,  733,  684,  662,
        0,   63,  676,  673,  671,    0,  733,  733,  658,   52,
      733,   53,   55,   57,  733,  650,  646,  645,   51,  662,
       74,   75,   76,   82,   77,   83,   79,   86,   85,   88,
       93,   87,   95,   98,   94,   91,   96,  112,  733,  603,
      733,  641,    0,  733,  623,  656,  646,  733,  611,  641,
      733,   90,  635,  138,  632,  631,  733,  628,  733,  733,
       83,  733,  733,  733,  618,   95,  141,  140,  144,  733,
      733,  733,  143,  151,  154,  162,  172,  633,  113,  147,
      148,  163,  166,  151,  169,  179,  181,  186,  182,  189,

      629,  191,  194,  625,  192,  193,  206,  196,  201,  199,
      200,  203,  209,  208,  207,  211,  213,  214,  215,  216,
      733,  733,    0,  559,  229,  203,  604,  256,  265,   76,
      733,  591,   86,   90,  254,  255,  257,  261,  264,  283,
      285,  288,  204,  220,  225,  218,  274,  300,  284,  291,
      302,  303,  305,  306,  307,  308,  605,  309,  310,  312,
      313,  311,  314,  315,  317,  322,  320,  323,  327,  604,
      326,  330,  328,  331,  336,  603,  333,  335,  338,  549,
      597,  595,  333,  592,  368,  376,   87,  733,  579,  203,
      386,  733,  387,  331,  334,  385,  345,  594,  568,  346,

      348,  341,  389,  552,  351,  357,  365,  551,  550,  404,
      548,  362,  547,  344,  391,  405,  410,  411,  414,  546,
      415,  417,  422,  423,  545,  418,  416,  421,  543,  424,
      425,  543,  733,  427,  208,  427,  428,  210,  538,  537,
      429,  430,  431,  432,  536,  434,  525,  533,  435,  438,
      439,  531,  530,  442,  441,  445,  446,  447,  529,  448,
      527,  455,  525,  733,  452,  472,  450,  468,  524,  517,
      471,  733,  473,  516,  480,  514,  513,  510,  509,  508,
      482,  481,  488,  507,  490,  506,  349,  483,  228,  485,
      491,  493,  226,  223,  115,  114,  494,  500,  496,  501,

      504,  505,  506,  109,  733,  557,  570,  583,  593,  601,
      613,  619,  623,  633,  636,  648,  658,  663,  667,  674,
      683,  692,  703,  710,  720
    } ;

static const flex_int16_t yy_def[326] =
    {   0,
      305,    1,  306,  306,  305,  305,  305,  305,  305,  305,
      307,  308,  309,  310,  305,  311,  305,  305,  305,  305,
      305,  305,  305,  312,  305,  305,  305,  305,  313,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  305,  305,
      305,  315,  316,  305,  305,  305,  305,  305,  305,  308,
      305,  308,  309,  317,  310,  310,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  312,  312,  318,  312,  305,
      305,  305,  313,  313,  319,  313,  320,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      305,  305,  316,  305,  305,  308,  321,  317,  322,  305,
      305,  305,  305,  305,  318,  318,  319,  313,  319,  323,
      320,  324,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  305,
      305,  305,  308,  321,  322,  322,  305,  305,  305,  305,
      323,  305,  325,  324,  324,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  305,  305,  308,  305,  325,  325,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  305,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  305,  308,  314,  314,  314,  314,  314,
      314,  305,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  308,  314,  314,  314,  314,  314,  314,  314,
      314,  308,  314,  314,  314,  314,  308,  308,  308,  308,

      308,  308,  308,  308,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305
    } ;

static const flex_int16_t yy_nxt[797] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,    6,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   30,   30,   30,
       30,   30,   31,    6,    6,    6,    6,   30,   32,   33,
       34,   35,   36,   37,   30,   38,   30,   39,   40,   41,
       30,   42,   43,   44,   45,   46,   47,   48,   30,   30,
       49,   50,   51,   54,   54,   61,   70,   62,   73,   72,
       83,   71,   71,   74,   75,   84,   76,   87,   87,   87,
       87,   77,   87,    6,   55,   87,   87,   86,   87,   87,
       87,   87,   61,   79,   87,  187,   87,   87,   87,   87,

      132,   87,  133,  132,   89,  133,  187,  190,  126,  134,
      188,   61,   75,   91,   76,   87,   87,   87,   87,   77,
       92,  188,  102,   94,   96,  103,   93,   90,  101,  100,
       98,   79,   95,   99,  105,   97,  107,  108,  115,  106,
      116,  143,  109,  110,  117,  127,  118,  104,  111,  119,
       87,   87,  112,  113,   87,  114,  120,  128,  305,  135,
       77,  305,   83,   79,   79,   77,   87,   84,   79,   87,
       83,  130,   87,  137,  128,   84,  135,   79,  138,   86,
       79,   86,   87,  140,   87,   87,  138,   86,  144,   87,
      137,  141,   87,  148,   87,   87,   87,   87,   86,   87,

      146,  145,   87,   87,   87,   61,   87,   87,  141,   87,
       87,   87,   87,   87,   87,  147,   87,   87,   87,   87,
      235,   87,  235,   87,  149,  235,   87,  235,   87,   87,
      196,   87,  150,  164,  153,  151,  152,  181,  159,  156,
      168,  266,  166,  154,  155,  157,  160,  170,  172,  161,
      158,  165,  167,  171,  176,  169,  173,  197,  183,  177,
      162,  179,  163,  127,  174,  175,  198,  178,  182,  182,
      199,  182,  127,  135,  135,  128,  137,   87,   79,   79,
       86,  138,  182,  137,  185,  138,  191,   87,  138,  130,
      135,  135,  128,  137,   87,  192,  140,   86,  130,  140,

      137,  185,  191,   87,  141,   87,   87,  194,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,  191,
       87,  141,  203,   87,  194,   87,   87,  200,  201,   87,
       87,   87,  204,   87,   87,   61,   87,  202,   87,   87,
      206,   87,  140,  205,   87,  140,  207,   87,   87,   87,
      194,   87,   87,  194,   87,  216,  208,  210,  214,  212,
       87,  209,  213,  211,  217,   87,  215,  194,   87,  218,
      194,  219,  222,  229,  220,  127,  227,  221,  226,  225,
      224,  228,  223,  127,  230,  231,  234,  185,   87,  191,
      191,  239,   87,  241,   87,  185,  242,  249,  192,  192,

      240,  130,  246,  244,  185,  191,  236,   87,   87,  130,
      238,  245,  185,   87,   87,  247,  248,   87,   87,   87,
       87,   87,  191,  236,   87,   87,   87,   87,   87,   61,
      191,  191,   87,   87,   87,   87,  243,   87,   87,  192,
      192,   87,   87,  250,   87,   87,  236,  236,   87,   87,
       87,   87,  252,   87,   61,  254,  256,  251,   87,  260,
      255,  257,  258,  236,  236,  253,  263,  259,  261,  262,
      283,   87,  269,  271,   87,   87,   87,  268,  267,  265,
      277,  270,  276,   87,   87,   87,   87,  274,   87,  273,
       61,  280,  275,   87,   87,   61,   61,  281,   61,  278,

      279,  284,   61,   61,  282,  285,   61,   61,   61,   87,
       87,   87,   87,   87,  288,  287,   87,   87,  299,   87,
       87,  289,  286,  290,  291,  295,  292,   87,   87,  304,
       87,  293,   87,   87,   87,  294,   87,  272,  297,   87,
       87,   87,  301,  298,  296,  264,   87,  300,   87,   87,
       87,   87,  303,   87,   87,   87,  302,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       59,   87,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   64,   87,  189,  127,

      233,   64,  233,  232,   64,   66,   87,   87,   87,   66,
      189,  127,   66,   68,  180,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   78,   78,   87,   78,
       78,   85,   87,   85,   85,   88,   87,  134,  131,   65,
       65,   88,   63,   61,   88,  122,  125,  122,  123,   57,
      123,  123,  123,  123,  123,  123,  123,   56,  123,  123,
      123,  129,  124,   81,  121,   87,  129,   82,   81,  129,
      129,  136,   80,  136,  136,  139,   69,  139,  139,  142,
       67,   65,  142,   63,   58,  142,  184,   57,   56,  305,
       52,  184,  305,  305,  184,  186,  305,  305,  305,  305,

      186,  305,  305,  186,  186,  193,  305,  305,  305,  193,
      305,  193,  305,  305,  193,  195,  305,  305,  195,  305,
      305,  195,  237,  305,  305,  305,  237,  305,  237,  305,
      305,  237,    5,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305

    } ;

static const flex_int16_t yy_chk[797] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   12,   20,   12,   23,   22,
       29,   20,   22,   23,   24,   29,   24,   31,   32,   33,
       35,   24,   37,    3,    4,   34,   36,   29,   39,   38,
       42,   40,   62,   24,   46,  130,   41,   45,   43,   47,

       71,   44,   71,  133,   31,  133,  187,  134,   62,  134,
      130,  304,   76,   33,   76,   48,   89,  296,  295,   76,
       33,  187,   39,   34,   35,   40,   33,   32,   38,   37,
       36,   76,   34,   36,   41,   35,   43,   44,   45,   42,
       46,   89,   44,   44,   46,   64,   47,   40,   44,   48,
       90,   91,   44,   44,   94,   44,   48,   64,   77,   78,
       77,   79,   83,   79,   78,   77,   92,   83,   79,   93,
       84,   64,   95,   85,   64,   84,   78,   77,   85,   83,
       79,   86,   96,   87,   97,   99,   86,   84,   90,   98,
       85,   87,  100,   94,  102,  105,  106,  103,   86,  108,

       92,   91,  110,  111,  109,  126,  112,  143,   87,  107,
      115,  114,  113,  238,  116,   93,  117,  118,  119,  120,
      190,  146,  190,  144,   95,  235,  294,  235,  145,  293,
      143,  289,   96,  108,   99,   97,   98,  125,  106,  103,
      112,  238,  110,  100,  102,  103,  107,  113,  115,  107,
      105,  109,  111,  114,  117,  112,  116,  144,  126,  118,
      107,  120,  107,  128,  116,  116,  145,  119,  125,  125,
      146,  125,  129,  135,  136,  128,  137,  147,  135,  136,
      138,  137,  125,  139,  129,  138,  140,  149,  139,  128,
      135,  136,  128,  137,  150,  140,  141,  138,  129,  142,

      139,  129,  140,  148,  141,  151,  152,  142,  153,  154,
      155,  156,  158,  159,  162,  160,  161,  163,  164,  140,
      165,  141,  149,  167,  142,  166,  168,  147,  147,  171,
      169,  173,  150,  172,  174,  183,  177,  148,  178,  175,
      152,  179,  194,  151,  202,  195,  153,  214,  197,  200,
      194,  201,  287,  195,  205,  163,  154,  156,  161,  159,
      206,  155,  160,  158,  164,  212,  162,  194,  207,  165,
      195,  166,  169,  177,  167,  185,  174,  168,  173,  172,
      171,  175,  169,  186,  178,  179,  183,  185,  196,  191,
      193,  197,  203,  201,  215,  186,  202,  214,  191,  193,

      200,  185,  207,  205,  185,  191,  193,  210,  216,  186,
      196,  206,  186,  217,  218,  210,  212,  219,  221,  227,
      222,  226,  191,  193,  228,  223,  224,  230,  231,  234,
      236,  237,  241,  242,  243,  244,  203,  246,  249,  236,
      237,  250,  251,  215,  255,  254,  236,  237,  256,  257,
      258,  260,  217,  267,  265,  219,  222,  216,  262,  227,
      221,  223,  224,  236,  237,  218,  231,  226,  228,  230,
      265,  268,  243,  246,  271,  266,  273,  242,  241,  234,
      255,  244,  254,  275,  282,  281,  288,  250,  290,  249,
      283,  258,  251,  285,  291,  292,  297,  260,  299,  256,

      257,  266,  298,  300,  262,  267,  301,  302,  303,  286,
      284,  280,  279,  278,  273,  271,  277,  276,  298,  274,
      270,  275,  268,  281,  282,  290,  283,  269,  263,  303,
      261,  285,  259,  253,  252,  288,  248,  247,  292,  245,
      240,  239,  300,  297,  291,  232,  229,  299,  225,  220,
      213,  211,  302,  209,  208,  204,  301,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      307,  199,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  309,  198,  189,  184,

      182,  309,  181,  180,  309,  310,  176,  170,  157,  310,
      132,  127,  310,  311,  124,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  312,  312,  104,  312,
      312,  313,  101,  313,  313,  314,   88,   75,   68,   66,
       65,  314,   63,   60,  314,  315,   59,  315,  316,   57,
      316,  316,  316,  316,  316,  316,  316,   56,  316,  316,
      316,  317,   55,   52,   50,   30,  317,   28,   27,  317,
      317,  318,   26,  318,  318,  319,   19,  319,  319,  320,
       15,   14,  320,   13,   10,  320,  321,    9,    7,    5,
        2,  321,    0,    0,  321,  322,    0,    0,    0,    0,

      322,    0,    0,  322,  322,  323,    0,    0,    0,  323,
        0,  323,    0,    0,  323,  324,    0,    0,  324,    0,
        0,  324,  325,    0,    0,    0,  325,    0,  325,    0,
        0,  325,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
int lineno = 1;
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

// 2-31 defined as keywords
#define BREAK 2
#define CASE 3
#define CHAR 4
#define CONST 5
#define CONTINUE 6
#define DEFAULT 7
#define DO 8
#define DOUBLE 9
#define ELSE 10
#define MY 11
#define EXTERN 12
#define FLOAT 13
#define FOR 14
#define IF 16
#define INT 17
#define LONG 18
#define REGISTER 19
#define RETURN 20
#define SHORT 21
#define SIGNED 22
#define USE 23
#define STATIC 24
#define STRUCT 25
#define SWITCH 26

#define UNION 28
#define UNSIGNED 29
#define VOID 30
#define SUBT 31

#define SUB 33 
#define IDENTIFIER 100
#define SLC 34
#define MLCS 35
#define MLCE 36
// 37 - 52 are defined as operator
#define LEQ 37
#define GEQ 38
#define EQEQ 39
#define NEQ 40
#define LOR 41
#define LAND 42
#define ASSIGN 43
#define PLUS 44
#define MULT 46
#define DIV 47
#define MOD 48
#define LESSER 49
#define GREATER 50
#define INCR 51
#define DECR 52

#define COMMA 53   //special symbol
#define SEMI 54         //special symbol

#define HEADER 55
#define MAIN 56


#define SCANF 58
#define DEFINE 59

#define INT_CONST 60
#define FLOAT_CONST 61

#define TYPE_SPEC 62

#define DQ 63        //special symbol

#define OBO 64        //special symbol
#define OBC 65         //special symbol
#define CBO 66        //special symbol
#define CBC 67         //special symbol
#define HASH 68       //special symbol

#define ARR 69
#define FUNC 70

#define NUM_ERR 71
#define UNKNOWN 72

#define CHAR_CONST 73                         // character const
#define SIGNED_CONST 74                      // Signed const  
#define STRING_CONST 75                     //String const

#define VARIABLE 76
// 77-84 defined as Control flow
#define UNTIL 77
#define FOREACH 78
#define NEXT 79
#define LAST 80
#define REDO 81
#define GOTO 82
#define WHILE 83
#define THEN 84

#define HASH_BANG 90
// 91 and 92 are pragma in perl
#define WARNINGS 91
#define STRICT 92
  

#define VARIABLE2 101    //array in perl   (data type)
#define VARIABLE3 102     //hash in perl   (data type)
#define SHEBANG 110
// pre defined function   
#define REVERSE 120
#define MAP 121
#define PRINT 57 
#define SORT 122
#define MULTILINECOMMENTBEGIN  150
#define MULTILINECOMMENTEND 151
#line 843 "lex.yy.c"

#line 845 "lex.yy.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 146 "lexer.l"

#line 1068 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 733 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 147 "lexer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 148 "lexer.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 149 "lexer.l"
return STRING_CONST;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 150 "lexer.l"
return CHAR_CONST;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 151 "lexer.l"
{lineno++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 152 "lexer.l"
return SHEBANG;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 153 "lexer.l"
return BREAK;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "lexer.l"
return REDO;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 155 "lexer.l"
return LAST;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 156 "lexer.l"
return GOTO;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 157 "lexer.l"
return UNTIL;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "lexer.l"
return NEXT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 159 "lexer.l"
return CASE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 160 "lexer.l"
return CHAR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "lexer.l"
return CONST;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "lexer.l"
return CONTINUE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 163 "lexer.l"
return USE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "lexer.l"
return DEFAULT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 "lexer.l"
return DO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "lexer.l"
return SUB;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 167 "lexer.l"
return DOUBLE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "lexer.l"
return ELSE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 169 "lexer.l"
return MY;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "lexer.l"
return EXTERN;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 171 "lexer.l"
return FLOAT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "lexer.l"
return FOR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 173 "lexer.l"
return WARNINGS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 174 "lexer.l"
return STRICT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 175 "lexer.l"
return IF;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 177 "lexer.l"
return REGISTER;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 178 "lexer.l"
return RETURN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 179 "lexer.l"
return SHORT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 180 "lexer.l"
return SIGNED;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 181 "lexer.l"
return THEN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 182 "lexer.l"
return STATIC;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 183 "lexer.l"
return STRUCT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 184 "lexer.l"
return SWITCH;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 185 "lexer.l"
return FOREACH;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 186 "lexer.l"
return UNION;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 187 "lexer.l"
return UNSIGNED;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 188 "lexer.l"
return VOID;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 189 "lexer.l"
return REVERSE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 190 "lexer.l"
return MAP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 191 "lexer.l"
return SORT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 194 "lexer.l"
return WHILE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 196 "lexer.l"
return PRINT;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 197 "lexer.l"
return SCANF;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 199 "lexer.l"
return IDENTIFIER;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 200 "lexer.l"
return VARIABLE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 201 "lexer.l"
return VARIABLE2;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 202 "lexer.l"
return VARIABLE3;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 204 "lexer.l"
return SIGNED_CONST;
	YY_BREAK
/* ---------------------------------------------------------------------------------------Operators defined ---------------------------------------------------------------------------------------------------------- */
case 53:
YY_RULE_SETUP
#line 206 "lexer.l"
return SLC;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 207 "lexer.l"
return MLCS;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 208 "lexer.l"
return MLCE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 210 "lexer.l"
return LEQ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 211 "lexer.l"
return GEQ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 212 "lexer.l"
return EQEQ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 213 "lexer.l"
return NEQ;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 214 "lexer.l"
return LOR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 215 "lexer.l"
return LAND;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 216 "lexer.l"
return ASSIGN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 217 "lexer.l"
return PLUS;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 218 "lexer.l"
return SUBT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 219 "lexer.l"
return MULT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 220 "lexer.l"
return DIV;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 221 "lexer.l"
return MOD;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 222 "lexer.l"
return LESSER;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 223 "lexer.l"
return GREATER;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 224 "lexer.l"
return INCR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 225 "lexer.l"
return DECR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 227 "lexer.l"
return COMMA;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 228 "lexer.l"
return SEMI;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 233 "lexer.l"
return HEADER;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 235 "lexer.l"
return MAIN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 237 "lexer.l"
return INT_CONST;                             // int const
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 238 "lexer.l"
return FLOAT_CONST;          // float const
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 242 "lexer.l"
printf("Single LineComment\n",lineno);     /* single line comments*/
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 246 "lexer.l"
{ BEGIN(comment);}  printf("Starting multi line commenting\n");                         /* Multi line comments*/
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 247 "lexer.l"
/* eat anything that's not a '=' */
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 248 "lexer.l"
++lineno;
	YY_BREAK
case 82:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "lexer.l"
{BEGIN(INITIAL);}  printf("Comment End and begin initial code\n");
	YY_BREAK
/*------------------------------------------------special symbol --------------------------------------------------------- */
case 83:
YY_RULE_SETUP
#line 255 "lexer.l"
return DQ;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 256 "lexer.l"
return OBO;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 257 "lexer.l"
return OBC;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 258 "lexer.l"
return CBO;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 259 "lexer.l"
return CBC;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 260 "lexer.l"
return HASH;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 262 "lexer.l"
return ARR;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 263 "lexer.l"
return FUNC;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 264 "lexer.l"
return NUM_ERR;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 265 "lexer.l"
return UNKNOWN;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 266 "lexer.l"
ECHO;
	YY_BREAK
#line 1599 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 305);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 266 "lexer.l"

 //--------------------------------------------------------------------------------------from line 255 -327  we have defined a hash table to  to store the output in sequence ------------------------------------------------
struct node
{
	char token[100];
    	char attr[100];
	struct node *next;
};

struct hash
{
	struct node *head;
	int count;
};

struct hash hashTable[1000];
int eleCount = 1000;

struct node * createNode(char *token, char *attr)
{
	struct node *newnode;
	newnode = (struct node *) malloc(sizeof(struct node));
	strcpy(newnode->token, token);
	strcpy(newnode->attr, attr);
	newnode->next = NULL;
	return newnode;
}

int hashIndex(char *token)
{
	int hi=0;
	int l,i;
	for(i=0;token[i]!='\0';i++)
	{
		hi = hi + (int)token[i];
	}
	hi = hi%eleCount;
	return hi;
}

void insertToHash(char *token, char *attr)
{
	int flag=0;
	int hi;
	hi = hashIndex(token);
	struct node *newnode = createNode(token, attr);
	/* head of list for the bucket with index "hashIndex" */
	if (hashTable[hi].head==NULL)
	{
		hashTable[hi].head = newnode;
	        hashTable[hi].count = 1;
	        return;
	}
	struct node *myNode;
    	myNode = hashTable[hi].head;
	while (myNode != NULL)
    	{
        	if (strcmp(myNode->token, token)==0)
        	{
            		flag = 1;
            		break;
        	}
        	myNode = myNode->next;
    	}
	if(!flag)
	{
		//adding new node to the list
		newnode->next = (hashTable[hi].head);
		//update the head of the list and no of nodes in the current bucket
		hashTable[hi].head = newnode;
		hashTable[hi].count++;
	}
	return;
}
 //--------------------------------------function to display the hash table------------------------
void display()
{
    	struct node *myNode;
    	int i,j, k=1;
    	printf("-------------------------------------------------------------------");
    	printf("\nSNo \t|\tToken \t\t|\tToken Type \t\n");
        printf("-------------------------------------------------------------------\n");
    	for (i = 0; i < eleCount; i++)
    	{
        	if (hashTable[i].count == 0)
            		continue;
        	myNode = hashTable[i].head;
        	if (!myNode)
            		continue;
        	while (myNode != NULL)
        	{
					if(strcmp(myNode->attr,"SPECIAL SYMBOL")==0)
					{
						printf("%d\t\t", k++);
            			printf("T_%s\t\t\t", myNode->token);
            			printf("%d\t\n", *myNode->token);
					}
					else
					{
						printf("%d\t\t", k++);
						printf("T_%s\t\t\t", myNode->token);
						printf("%s\t\n", myNode->attr);
					}
            		myNode = myNode->next;
        	}
	}
   	return;
}
 // ---------------------------------------------------------------main function ----------------------------------------------------
int main()
{
	int scan, slcline=0, mlc=0, mlcline=0, dq=0, dqline=0;     //  pointers to iterate over the test file  
	yyin = fopen("test5.pl","r"); //add test case files here
	printf("\n\n");
	scan = yylex();
	while(scan)
	{
		if(lineno == slcline)
		{
			scan = yylex();
			continue;
		}
		if(lineno!=dqline && dqline!=0)
		{
			if(dq%2!=0)
				printf("\n******** ERROR!! INCOMPLETE STRING at Line %d ********\n\n", dqline);
			dq=0;
		}
		if(scan==110  && mlc==0)
		{
			printf("%s\t\t\tHASH_BANG\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "HASH_BANG");
		}
	
		if(scan==101  && mlc==0)
		{
			printf("%s\t\t\tARRAY\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "ARRAY");
		}
		
		if(scan==102  && mlc==0)
		{
			printf("%s\t\t\tHASH\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "HASH");
		}
		if((scan>=1 && scan<=32) && mlc==0)
		{
			printf("%s\t\t\tKEYWORD\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "KEYWORD");
		}
		if((scan>=91 && scan<=92) && mlc==0)
		{
			printf("%s\t\t\tPRAGMA\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "PRAGMA");
		}
		if(scan==33 && mlc==0) 
		{
			printf("%s\t\t\tSUBROUTINE\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "SUBROUTINE");
		}
		if(scan==100 && mlc==0) 
		{
			printf("%s\t\t\tIDENTIFIER\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "IDENTIFIER");
		}
	
		
		if((scan>=37 && scan<=52) && mlc==0)
		{
			printf("%s\t\t\tOPERATOR\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "OPERATOR");
		}
		if((scan==53||scan==54||scan==63||(scan>=64 && scan<=68)) && mlc==0)
		{
			printf("%s\t\t\tSPECIAL SYMBOL\t\t\tLine %d\n", yytext, lineno);
			if(scan==63)
			{
				dq++;
				dqline = lineno;
			}
			insertToHash(yytext,"SPECIAL SYMBOL");
		}
		if(scan==55 && mlc==0)
		{
			printf("%s\tHEADER\t\t\t\tLine %d\n",yytext, lineno);
		}
		if(scan==56 && mlc==0)
		{
			printf("%s\t\t\tMAIN FUNCTION\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "IDENTIFIER");
		}
		if((scan==57 || scan==58||scan==120||scan==121||scan==122) && mlc==0)
		{
			printf("%s\t\t\tPRE DEFINED FUNCTION\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "PRE DEFINED FUNCTION");
		}
		if(scan==59 && mlc==0)
		{
			printf("%s\t\t\tPRE PROCESSOR DIRECTIVE\t\tLine %d\n", yytext, lineno);
		}
		if(scan==60 && mlc==0)
		{
			printf("%s\t\t\tINTEGER CONSTANT\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "INTEGER CONSTANT");
		}
		if(scan==61 && mlc==0)
		{
			printf("%s\t\t\tFLOATING POINT CONSTANT\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "DOUBLE");
		}
		if(scan==62 && mlc==0)
		{
			printf("%s\t\t\tTYPE SPECIFIER\t\t\tLine %d\n", yytext, lineno);
		}
		if(scan==69 && mlc==0)
		{
			printf("%s\t\t\tARRAY\t\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "ARRAY");
		}
		
		if(scan==71 && mlc==0)
		{
			printf("\n******** ERROR!! CONSTANT ERROR %s at Line %d ********\n\n", yytext, lineno);
		}
		if(scan==72 && mlc==0)
		{
			printf("\n******** ERROR!! UNKNOWN TOKEN T_%s at Line %d ********\n\n", yytext, lineno);
		}
		if(scan==73 && mlc==0)
		{
			printf("%s\t\t\tCHARACTER CONSTANT\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "CHARACTER CONSTANT");
		}
		if(scan==74 && mlc==0)
		{
			printf("%s\t\t\tSIGNED CONSTANT\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "SIGNED CONSTANT");
		}
		if(scan==75 && mlc==0)
		{
			printf("%s\t\t\tSTRING CONSTANT\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "STRING_CONSTANT");
		}
		if(scan==76 && mlc==0)
		{
			printf("%s\t\t\tSCALAR\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "SCALAR");
		}
		if((scan>=77 && scan<=84) && mlc==0)
		{
			printf("%s\t\t\tCONTROLFLOW\t\t\tLine %d\n", yytext, lineno);
			insertToHash(yytext, "CONTROLFLOW");
		}
		scan = yylex();
	}
	if(mlc==1)
		printf("\n******** ERROR!! UNMATCHED COMMENT STARTING at Line %d ********\n\n",mlcline);
	printf("\n");
	printf("\n\t******** SYMBOL TABLE ********\t\t\n");
	display();
        printf("-------------------------------------------------------------------\n\n");
}
int yywrap()
{
	return 1;
}

